server:
  port: 8082
spring:
  application:
    name: twitter-clone-comments-service
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${DB_HOST:mongodb://localhost:27017/tc_comments_db}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:1234}
posts-service:
  url: ${POST_URL:http://localhost:8081/v1/posts}
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info